### ISSUE TITLE
Add Admin Issue 

### ISSUE THREAD

**Issue by ngtalexander** [idurar/idurar-erp-crm#983] opened 2024-02-29 08:58 UTC
**Describe the bug**
Coming back again with the issue of the 400 error when trying to add an admin. Probably something is wrong on my end because on your website works, but when I try on my end it doesn't. 

**To Reproduce**

https://github.com/idurar/idurar-erp-crm/assets/156243001/2392139a-edd5-41d5-b108-a3e5f1f75391

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
EDIT: I can add everything else, from customers to invoices to offers etc(I can see the updates in database as well). The only problem is the admin.

**Comment by ravi-rautela** [comment] 2024-02-29 09:52
hey ngtalexander, can you tell me how i can login throw email and password in starting of my execution on my local machine.
I don't have any admin email and password

**Comment by filaliyasmine** [comment] 2024-02-29 10:18
Yes I tried the same steps and got the same error. I think that the problem is a backend error since there is no validator in the frontend.

**Comment by DarshanDixit05** [comment] 2024-03-02 10:17
Hey @slimskhab can I pick this issue?

**Comment by slimskhab** [comment] 2024-03-02 14:10
> Hey @slimskhab can I pick this issue?

Hey @DarshanDixit05, It's already fixed in this PR #984

**Closed** 2024-03-04 11:05 UTC
