### ISSUE TITLE
Bug/ on Dashboard Card 

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#371] opened 2023-08-29 14:47 UTC

**Comment by rkmdCodes** [comment] 2023-08-30 06:12
hi @salahlalami @Ando22 sir, can u elaborate more about the bugs?
I would like to work on this

**Comment by Ando22** [comment] 2023-08-30 08:09
Hi @rkmdCodes so the bug is the empty top card of the dashboards. it should return value because the data is there. also, the card should handle an empty state.

<img width="1439" alt="Screen Shot 2023-08-30 at 15 03 01" src="https://github.com/idurar/idurar-erp-crm/assets/38315094/3260cd3b-544a-46cf-bd4e-d0f9e5e18779">

**Comment by rkmdCodes** [comment] 2023-08-30 10:28
thanks  @Ando22 i am onto it ,

**Comment by rkmdCodes** [comment] 2023-08-30 15:02
hi @Ando22 @salahlalami  sir
I have created PR #378 which will close this issue
![image](https://github.com/idurar/idurar-erp-crm/assets/113243168/6fee3cf3-a06e-405f-9615-50ebf01e5e70)

**Comment by rkmdCodes** [comment] 2023-09-03 16:24
hi @salahlalami @Ando22 
The issue is now fixed by PR #409

**Closed** 2023-09-04 19:09 UTC
Labels: bug, Frontend
